name: Deploy Next

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  # Build job
  build:
    runs-on: self-hosted
    steps:
      # - uses: actions/checkout@v2
      - name: Run script file
        run: |
          chmod +x ~/fakepng-dev/deploy.sh
          ~/fakepng-dev/deploy.sh
        shell: bash
