name: Deploy Next

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  # Build job
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18.x"
      - name: Install dependencies
        run: npm install
      - name: Install PM2.js
        run: npm install pm2@latest -g
      - name: Build NEXT.js
        run: npm run build
      - name: Deploy NEXT.js
        run: pm2 start npm --name fakepng-dev -- run start -- -p 3000
