name: Deploy Next

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Run Container
        run: docker compose up -d --build
        env:
          NODE_ENV: production

      - name: Cleanup Unused Images
        run: docker image prune -f
